# 프라미스와 에러 핸들링

프라미스가 거부되면 제어 흐름이 제일 가까운 `rejection` 핸들러로 넘어가기 때문에 프라미스 체인으로 에러를 쉽게 처리할 수 있습니다.

가장 쉬운 에러 처리 방법은 체인 끝에 `.catch`를 붙이는 것입니다. 
정상적인 경우라면 `.catch`는 절대 트리거 되지 않습니다. 그런데 위쪽 프라미스 중 하나라도 거부되면 에러를 잡습니다.

<br><br>

## 암시적 try..catch

프라미스 executor와 프라미스 핸들러 코드 주위엔 '암시적 `try..catch`'가 있습니다.

아래 두 예시는 똑같이 동작합니다.

```js
new Promise((resolve, reject) => throw new Error();})
  .catch(alert);
  
new Promise((resolve, reject) => reject(new Error());})
  .catch(alert);
```

executor 주위의 '암시적 `try..catch`'는 스스로 에러를 잡고, 에러를 거부상태의 프라미스로 변경시킵니다.

이는 executor 함수뿐만 아니라 핸들러에서도 발생합니다.
`.then` 핸들러 안에서 `throw`로 에러를 던지면, 이 자체가 거부된 프라미스를 의미하게 됩니다.
따라서 가장 가까운 에러 핸들러로 넘어갑니다.

`throw`문이 명시적으로 만든 에러뿐만 아니라 모든 종류의 에러가 암시적 `try..catch`에서 처리됩니다. 

<br><br>

## 다시 던지기

`try..catch`와 유사하게 에러를 다시 던질 수 있습니다.

`.catch` 안에서 `throw`를 사용하면 가장 가까운 에러 핸들러로 넘어갑니다. 
여기서 에러가 성공적으로 처리되면 **가장 가까운 `.then` 핸들러**로 넘어가 실행이 이어집니다.

처리하지 못하면 에러를 다시 던지고, 이는 다음 `.catch`로 이어집니다. ([예시](https://ko.javascript.info/promise-error-handling#ref-3326:~:text=//%20%EC%8B%A4%ED%96%89%20%EC%88%9C%EC%84%9C%3A%20catch%20%2D%3E%20catch,%EA%B3%84%EC%86%8D%EB%90%A8%0A%0A%7D)%3B))

<br><br>

## 처리되지 못한 거부

예외를 처리해 줄 핸들러가 없다면 에러가 ‘갇혀버려’ 실무에선 끔찍한 일이 발생합니다.

자바스크립트 엔진은 프라미스 거부를 추적하다가 위와 같은 상황이 발생하면 전역 에러를 생성합니다. 

브라우저 환경에선 이런 에러를 `unhandledrejection` 이벤트([HTML 명세서](https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections))로 처리할 수 있습니다.

```js
window.addEventListener('unhandledrejection', function(event) {
  // unhandledrejection 이벤트엔 두 개의 특수 프로퍼티가 있습니다.
  alert(event.promise); // [object Promise] - 에러를 생성하는 프라미스
  alert(event.reason); // Error: 에러 발생! - 처리하지 못한 에러 객체
});

new Promise(function() {
  throw new Error("에러 발생!");
}); // 에러를 처리할 수 있는 .catch 핸들러가 없음
```
